// <auto-generated />
using System;
using InfoCollectorAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfoCollectorAPI.Migrations
{
    [DbContext(typeof(InfoCollectorDbContext))]
    [Migration("20250713180026_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("InfoCollectorAPI.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupOrUserName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupOrUserName")
                        .HasDatabaseName("IX_Messages_GroupOrUserName");

                    b.HasIndex("ReceivedDateTime")
                        .HasDatabaseName("IX_Messages_ReceivedDateTime");

                    b.ToTable("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
